BlockCrafting.addMultiblockStructure(MultiblockStructureBuilder.create('sapling')
    .pattern('ccc', 'ccc', 'cac','ccc')
    .pattern('cAc', 'cac', 'aba','cac')
    .pattern('ccc', 'ccc', 'cac','ccc')
    .where('a', 'slimeoverhaul:earth_slime_block')
    .where('b', 'minecraft:clay')
    .where('c', 'minecraft:air')
    .center('A', 'minecraft:dead_bush')
    .craftingItem('minecraft:air')
    .resultItem('minecraft:oak_sapling')
    .build()
)

BlockCrafting.addMultiblockStructure(MultiblockStructureBuilder.create('test1')
    .pattern('aaa', 'aaa', 'aaa')
    .pattern('aaa', 'aba', 'aaa')
    .pattern('aaa', 'aAa', 'aaa')
    .where('a', 'minecraft:cobblestone')//多方块结构1
    .where('b', 'minecraft:dirt')//多方块结构2
    .center('A', 'minecraft:cobblestone')//右键点击的位置
    .craftingItem('minecraft:stick')//合成的物品
    .resultEntity('minecraft:pig')//输出实体:pig
    .build()
)

BlockCrafting.addMultiblockStructure(MultiblockStructureBuilder.create('phantom')
    .pattern('ece', 'eee')
    .pattern('aba', 'ede')
    .pattern('eAe', 'eee')
    .where('a', 'minecraft:iron_bars')
    .where('b', 'minecraft:end_stone')
    .where('c', 'minecraft:end_rod')
    .where('d', 'botania:starfield')
    .where('e', 'minecraft:air')
    .center('A', 'botania:fel_pumpkin')
    .craftingItem('minecraft:leather')
    .resultEntity('minecraft:phantom')
    .build()
)

BlockCrafting.addMultiblockStructure(MultiblockStructureBuilder.create('crushing_wheel1')
    .pattern('eaaae')
    .pattern('aabaa')
    .pattern('abAba')
    .pattern('aabaa')
    .pattern('eaaae')
    .where('a', 'create:andesite_casing')
    .whereTag('b', 'minecraft:planks')
    .where('e', 'minecraft:air')
    .center('A', 'stone')
    .craftingItem('air')
    .resultItem('create:crushing_wheel')
    .build()
)

BlockCrafting.addMultiblockStructure(MultiblockStructureBuilder.create('crushing_wheel2')
    .pattern('eaaae')
    .pattern('aabaa')
    .pattern('abAba')
    .pattern('aabaa')
    .pattern('eaaae')
    .where('a', 'create:andesite_casing')
    .whereTag('b', 'minecraft:planks')
    .where('e', 'minecraft:air')
    .center('A', 'minecraft:andesite')
    .craftingItem('air')
    .resultItem('create:crushing_wheel')
    .build()
)

BlockCrafting.addMultiblockStructure(MultiblockStructureBuilder.create('crushing_wheel3')
    .pattern('eaaae')
    .pattern('aabaa')
    .pattern('abAba')
    .pattern('aabaa')
    .pattern('eaaae')
    .where('a', 'create:andesite_casing')
    .whereTag('b', 'minecraft:planks')
    .where('e', 'minecraft:air')
    .center('A', 'minecraft:diorite')
    .craftingItem('air')
    .resultItem('create:crushing_wheel')
    .build()
)

BlockCrafting.addMultiblockStructure(MultiblockStructureBuilder.create('crushing_wheel4')
    .pattern('eaaae')
    .pattern('aabaa')
    .pattern('abAba')
    .pattern('aabaa')
    .pattern('eaaae')
    .where('a', 'create:andesite_casing')
    .whereTag('b', 'minecraft:planks')
    .where('e', 'minecraft:air')
    .center('A', 'minecraft:granite')
    .craftingItem('air')
    .resultItem('create:crushing_wheel')
    .build()
)

BlockCrafting.addMultiblockStructure(MultiblockStructureBuilder.create('warden')
    .pattern('eae', 'aAa', 'ebe')
    .where('a', 'minecraft:sculk')
    .where('b', 'minecraft:carved_pumpkin')
    .where('e', 'minecraft:air')
    .center('A', 'minecraft:sculk_catalyst')
    .craftingItem('minecraft:sculk_vein')
    .resultEntity("minecraft:warden")
    .build()
)

