ServerEvents.entityLootTables(event => {
    event.modifyEntity('minecraft:warden', Loot =>{
        Loot.addPool(pool => {
            pool.addItem('minecraft:sculk_shrieker').weight(1).count(1)
            pool.addEmpty(2)
        })
    })

    event.modifyEntity('slimeoverhaul:earth_slime', Loot =>{
        Loot.addPool(pool => {
            pool.addItem('mysticalagriculture:dirt_essence').weight(1).count([1,2]).lootingEnchant(2,8)
        })
    })
    event.modifyEntity('slimeoverhaul:flame_slime', Loot =>{
        Loot.addPool(pool => {
            pool.addItem('mysticalagriculture:fire_essence').weight(1).count([1,2]).lootingEnchant(2,8)
        })
    })
})

ServerEvents.genericLootTables(e=>{
    e.addGeneric("tumbleweed:entities/tumbleweed",loot=>{
        loot.addPool(pool=>{
            pool.addItem('materialfactory:cactus_sandwich').weight(1)
            pool.addItem("minecraft:dead_bush").weight(1)
            pool.addItem('minecraft:stick').weight(3).count([1, 2])
            pool.addItem('notreepunching:plant_fiber').weight(2).count([1, 2])
            pool.addItem('minecraft:bone').weight(1).count([1, 2])
            pool.addItem('minecraft:rotten_flesh').weight(1).count(1)
            pool.addItem('minecraft:leather').weight(1).count(1)
            pool.addItem('exdeorum:stone_pebble').weight(1).count([1, 2])
            pool.addItem('minecraft:feather').weight(1).count(1)
            pool.addItem('notreepunching:flint_shard').weight(1).count(1)
            pool.addItem('minecraft:emerald').weight(1).count(1)
        })
    })
})

//普通废墟战利品
//食物
ServerEvents.blockLootTables(event =>{
    event.addBlock('materialfactory:metal_barrel',Loot=>{
        Loot.addPool(p=>{
            p.addEmpty(4)
            p.addItem('minecraft:potato').count([1,4]).weight(4)
            p.addItem('minecraft:carrot').count([1,4]).weight(4)
            p.addItem('minecraft:apple').count([1,2]).weight(4)
            p.addItem('minecraft:wheat_seeds').count([1,4]).weight(4)
            p.addItem('minecraft:beetroot_seeds').weight(4)
            p.addItem('minecraft:melon_seeds').count([1,2]).weight(4)
            p.addItem('minecraft:pumpkin_seeds').count([1,2]).weight(4)
            p.addItem('minecraft:pitcher_pod').count([1,2]).weight(4)
            p.addItem('thermal:flax_seeds').count([1,2]).weight(2)
            p.addItem('minecraft:glow_berries').count([1,3]).weight(4)
            p.addItem('minecraft:torchflower_seeds').weight(2)
            p.addItem('supplementaries:flax_seeds').weight(2)
            p.addItem('actuallyadditions:canola_seeds').weight(2)
            p.addItem('actuallyadditions:flax_seeds').weight(2)
            p.addItem('ars_nouveau:magebloom_crop').weight(2)
            p.addItem('thermal:amaranth_seeds').weight(2)
            p.addItem('thermal:barley_seeds').weight(2)
            p.addItem('thermal:corn_seeds').weight(2)
            p.addItem('thermal:onion_seeds').weight(2)
            p.addItem('thermal:radish_seeds').weight(2)
            p.addItem('thermal:rice_seeds').weight(2)
            p.addItem('thermal:sadiroot_seeds').weight(2)
            p.addItem('thermal:spinach_seeds').weight(2)
            p.addItem('thermal:bell_pepper_seeds').weight(2)
            p.addItem('thermal:eggplant_seeds').weight(2)
            p.addItem('thermal:green_bean_seeds').weight(2)
            p.addItem('thermal:peanut_seeds').weight(2)
            p.addItem('thermal:strawberry_seeds').weight(2)
            p.addItem('thermal:tomato_seeds').weight(2)
            p.addItem('thermal:hops_seeds').weight(2)
            p.addItem('thermal:tea_seeds').weight(2)
            p.addItem('thermal:frost_melon_seeds').weight(2)
            p.addItem('tconstruct:earth_slime_grass_seeds').weight(2)
            p.addItem('tconstruct:sky_slime_grass_seeds').weight(2)
            p.addItem('tconstruct:ender_slime_grass_seeds').weight(2)
            p.addItem('tconstruct:blood_slime_grass_seeds').weight(2)
            p.addItem('minecraft:cake').weight(2)
            p.addItem('thermal:stuffed_pumpkin').weight(2)
            p.addItem('thermal:carrot_cake').weight(2)
            p.addItem('thermal:chocolate_cake').weight(2)
            p.addItem('thermal:spice_cake').weight(2)
            p.addItem('create:blaze_cake').weight(2)
            p.addItem('createaddition:honey_cake').weight(2)
            p.addItem('createaddition:chocolate_cake').weight(2)
            p.addItem('create:creative_blaze_cake').weight(1)
            p.addTag('minecraft:flowers',true).weight(2)
            p.addTag('forge:mushrooms',true).weight(2)
            p.addTag('forge:crops',true).weight(2)
            p.addItem('avaritia:cosmic_meatballs').weight(1)
            p.addItem('artifacts:everlasting_beef').weight(1)
            p.rolls = ([1,3])
        })
    })

    event.addBlock('materialfactory:metal_crate',Loot=>{
        Loot.addPool(p=>{
            p.addEmpty(4)
            p.addItem('alltheores:copper_nugget').count([1,3]).weight(10)
            p.addItem('minecraft:iron_nugget').count([1,3]).weight(10)
            p.addItem('alltheores:tin_nugget').count([1,2]).weight(8)
            p.addItem('alltheores:zinc_nugget').count([1,2]).weight(8)
            p.addItem('alltheores:lead_nugget').count([1,2]).weight(8)
            p.addItem('alltheores:silver_nugget').count([1,2]).weight(8)
            p.addItem('alltheores:nickel_nugget').count([1,2]).weight(8)
            p.addItem('alltheores:aluminum_nugget').count([1,2]).weight(8)
            p.addItem('alltheores:osmium_nugget').count([1,2]).weight(8)
            p.addItem('alltheores:platinum_nugget').count([1,2]).weight(8)
            p.addItem('alltheores:uranium_nugget').count([1,2]).weight(8)
            p.addItem('alltheores:steel_nugget').count([1,2]).weight(8)
            p.addItem('alltheores:invar_nugget').count([1,2]).weight(8)
            p.addItem('alltheores:electrum_nugget').count([1,2]).weight(8)
            p.addItem('alltheores:bronze_nugget').count([1,2]).weight(8)
            p.addItem('alltheores:iridium_nugget').count([1,2]).weight(8)
            p.addItem('alltheores:enderium_nugget').count([1,2]).weight(8)
            p.addItem('alltheores:lumium_nugget').count([1,2]).weight(8)
            p.addItem('alltheores:signalum_nugget').count([1,2]).weight(8)
            p.addItem('alltheores:constantan_nugget').count([1,2]).weight(8)
            p.addItem('alltheores:brass_nugget').count([1,2]).weight(8)
            // p.addItem('opolisutilities:mini_charcoal').count([1,2]).weight(8)
            // p.addItem('opolisutilities:mini_coal').count([1,2]).weight(8)
            p.rolls = ([1,3])
        })
    })
    event.addBlock('materialfactory:brown_crate',Loot=>{
        Loot.addPool(p=>{
            p.addEmpty(4)
            p.addItem('minecraft:quartz').count([1,8]).weight(8)
            p.addItem('minecraft:amethyst_shard').count([1,4]).weight(4)
            p.addItem('minecraft:stick').count([4,16]).weight(12)
            p.addItem('minecraft:flint').count([1,4]).weight(12)
            p.addItem('minecraft:bone').count([4,8]).weight(12)
            p.addItem('minecraft:tripwire').count([4,12]).weight(12)
            p.addItem('minecraft:leather').count([1,2]).weight(8)
            p.addItem('minecraft:honeycomb').count([3]).weight(4)
            p.addItem('minecraft:ink_sac').count([1,2]).weight(8)
            p.addItem('minecraft:glow_ink_sac').count([1,2]).weight(8)
            p.addItem('minecraft:scute').count([1,2]).weight(4)
            p.addItem('minecraft:slime_ball').count([4,16]).weight(12)
            p.addItem('minecraft:clay_ball').count([16,32]).weight(8)
            p.addItem('minecraft:prismarine_shard').count([1,2]).weight(8)
            p.addItem('minecraft:prismarine_crystals').count([1,2]).weight(8)
            p.addItem('minecraft:nautilus_shell').count([1]).weight(4)
            p.addItem('minecraft:heart_of_the_sea').count([1]).weight(1)
            p.addItem('minecraft:fire_charge').count([1,3]).weight(8)
            p.addItem('minecraft:blaze_rod').count([1,2]).weight(8)
            p.addItem('minecraft:nether_star').count([1]).weight(1)
            p.addItem('minecraft:ender_pearl').count([1,2]).weight(10)
            p.addItem('minecraft:paper').count([3,6]).weight(12)
            p.addItem('minecraft:glass_bottle').count([1,3]).weight(12)
            p.addItem('minecraft:nether_wart').count([1,4]).weight(6)
            p.addItem('minecraft:redstone').count([4,16]).weight(14)
            p.addItem('minecraft:glowstone_dust').count([1,16]).weight(10)
            p.addItem('minecraft:gunpowder').count([1,16]).weight(14)
            p.addItem('minecraft:sugar').count([3,6]).weight(10)
            p.addItem('minecraft:rabbit_foot').count([1]).weight(2)
            p.addItem('minecraft:spider_eye').count([1,2]).weight(14)
            p.addItem('minecraft:magma_cream').count([1,2]).weight(8)
            p.addItem('minecraft:ghast_tear').count([1]).weight(1)
            p.addItem('minecraft:phantom_membrane').count([1,3]).weight(6)
            p.addItem('minecraft:book').count([1,6]).weight(8)
            p.addItem('minecraft:bowl').count([1]).weight(12)
            p.rolls = ([1,3])
        })
    })
    event.addBlock('materialfactory:copper_crate',Loot=>{
        Loot.addPool(p=>{
            p.addEmpty(4)
            p.addItem('create:andesite_alloy').count([1,4]).weight(16)
            p.addItem('create:shaft').count([1,2]).weight(14)
            p.addItem('create:cogwheel').count([1,2]).weight(12)
            p.addItem('create:large_cogwheel').count([1,2]).weight(12)
            p.addItem('create:andesite_casing').count([1,2]).weight(12)
            p.addItem('create:belt_connector').count([1,3]).weight(12)
            p.addItem('create:fluid_pipe').count([1,4]).weight(12)
            p.addItem('create:brass_casing').count([1,2]).weight(12)
            p.addItem('create:copper_casing').count([1,2]).weight(12)
            p.addItem(Item.of('create:super_glue', '{Damage:0}')).count([1]).weight(10)
            p.addItem('create:rose_quartz').count([1,2]).weight(6)
            p.addItem('create:propeller').count([1]).weight(6)
            p.addItem(Item.of('create:sand_paper', '{Damage:0}')).count([1]).weight(6)
            p.addItem('create:electron_tube').count([1]).weight(2)
            p.addItem('create:precision_mechanism').count([1]).weight(2)
            p.addItem('create:blaze_cake').count([1]).weight(2)
            p.rolls = ([1,3])
        })
    })
    event.addBlock('materialfactory:blue_crate',Loot=>{
        Loot.addPool(p=>{
            p.addEmpty(4)
            p.addItem('ae2:calculation_processor_press').count([1]).weight(10)
            p.addItem('ae2:engineering_processor_press').count([1]).weight(10)
            p.addItem('ae2:logic_processor_press').count([1]).weight(10)
            p.addItem('ae2:silicon_press').count([1]).weight(10)
            p.addItem('ae2:certus_quartz_crystal').count([2,8]).weight(16)
            p.addItem('ae2:silicon').count([2,8]).weight(16)
            p.addItem('ae2omnicells:multidimensional_expansion_print_press').count([1]).weight(6)
            p.addItem('ae2omnicells:omni_link_print_press').count([1]).weight(6)
            p.addItem('ae2omnicells:complex_link_print_press').count([1]).weight(6)
            p.addItem('ae2:printed_calculation_processor').count([1]).weight(10)
            p.addItem('ae2:printed_engineering_processor').count([1]).weight(10)
            p.addItem('ae2:printed_logic_processor').count([1]).weight(10)
            p.addItem('ae2:logic_processor').count([1]).weight(8)
            p.addItem('ae2:calculation_processor').count([1]).weight(8)
            p.addItem('ae2:engineering_processor').count([1]).weight(8)
            p.addItem('ae2:sky_dust').count([4,16]).weight(16)
            p.addItem('ae2:ender_dust').count([4,16]).weight(16)
            p.addItem('ae2:flawless_budding_quartz').count([1]).weight(1)
            p.addItem('ae2:flawed_budding_quartz').count([1]).weight(4)
            p.addItem('ae2:chipped_budding_quartz').count([1]).weight(6)
            p.addItem('ae2:damaged_budding_quartz').count([1]).weight(8)
            p.addItem('ae2:quartz_block').count([1]).weight(10)
            p.addItem('ae2:quartz_glass').count([1,4]).weight(12)
            p.addItem('ae2:sky_stone_block').count([1,3]).weight(12)
            p.addItem('mekanism:yellow_cake_uranium').count([4,12]).weight(8)
            p.addItem('mekanism:basic_control_circuit').count([1]).weight(8)
            p.addItem('mekanism:advanced_control_circuit').count([1]).weight(6)
            p.addItem('mekanism:elite_control_circuit').count([1]).weight(4)
            p.addItem('mekanism:ultimate_control_circuit').count([1]).weight(2)
            p.addItem('mekanism:alloy_infused').count([1]).weight(8)
            p.addItem('mekanism:alloy_reinforced').count([1]).weight(4)
            p.addItem('mekanism:alloy_atomic').count([1]).weight(2)
            p.addItem('mekanism:teleportation_core').count([1]).weight(1)
            p.addItem('megacells:accumulation_processor_press').count([1]).weight(8)
            p.addItem('appflux:energy_processor_press').count([1]).weight(8)
            p.addItem('megacells:printed_accumulation_processor').count([1]).weight(8)
            p.addItem('megacells:accumulation_processor').count([1]).weight(6)
            p.addItem('appflux:printed_energy_processor').count([1]).weight(8)
            p.addItem('appflux:energy_processor').count([1]).weight(6)
            p.addItem('ae2:blank_pattern').count([1]).weight(8)
            p.addItem('ae2:basic_card').count([1]).weight(8)
            p.addItem('ae2:advanced_card').count([1]).weight(6)
            
            p.rolls = ([1,3])
        })
    })

})